version: "3.7"

networks:
  main:

services:
  postgres:
    image: "postgres:13.1"
    environment:
      POSTGRES_DB: sidegig
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - pg

  web:
    build:
      context: .
    environment:
      - PORT=80
      - DATABASE_URL
    ports:
      - ${WEB_PORT}:80
    networks:
      main:
        aliases:
          - web
    command: lerna exec --scope @tuxsudo/sidegig-web --stream "npx prisma migrate deploy --preview-feature && lerna run start --scope @tuxsudo/sidegig-web --stream"
