version: "3.7"

networks:
  main:

services:
  postgres:
    image: "postgres:13.1"
    environment:
      POSTGRES_DB: sidegig
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - pg

  web:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://user:password@pg:5432/sidegig?schema=public
      - LOGGER_NAME
      - LOGGER_LEVEL
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - web
    command: npm start
